apiversion: v2
name: onecx-ai
version: 0.0.0
appversion: 0.0.0
dependencies:
- name: helm-product
  version: ^0
  repository: oci://ghcr.io/onecx/charts
  alias: product
- name: onecx-ai-management-svc
  version: "*-0"
  repository: oci://ghcr.io/onecx-apps/charts
  condition: "deployment.svc"
  alias: "svc"